name: Build Test

on:
  push:
    branches:
      - main
    paths:
      - '!.github/**'
  workflow_dispatch:

jobs:
  build-test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - name: Install dependencies 🔧
        run: yarn
      - name: Eslint Fix 🔧
        run: yarn lint
