name: Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - name: Restore cached ./node_modules
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: ${{ runner.os }}-yarn-lock-${{ hashFiles('./yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-lock-
      - name: Install dependencies 🔧
        run: yarn install --frozen-lockfile --registry=https://registry.npmjs.org/
      - name: Eslint Fix 🔧
        run: yarn lint
      - name: Build app 🔧
        run: yarn build
      - name: Deploy to branch🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: deploy
          folder: dist
