name: Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - name: Restore cached ./node_modules
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: ${{ runner.os }}-yarn-lock-${{ hashFiles('./yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-lock-
      - name: Install dependencies 🔧
        run: yarn install --frozen-lockfile

  lint:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - name: Restore cached ./node_modules
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: ${{ runner.os }}-yarn-lock-${{ hashFiles('./yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-lock-
      - name: Eslint Fix 🔧
        run: yarn lint

  build:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - name: Restore cached ./node_modules
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: ${{ runner.os }}-yarn-lock-${{ hashFiles('./yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-lock-
      - name: Build app 🔧
        run: yarn build
      - name: Deploy to branch🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: deploy
          folder: dist

  deploy:
    runs-on: ubuntu-latest
    needs: [lint,build]
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          script: |
            cd ${{ secrets.PATH }}
            git pull --rebase
