name: Auto Test

on:
  push:
    branches:
      - 'main'
      - 'dev'
    paths-ignore:
      - '.github/**'
  pull_request:
    branches-ignore:
      - 'deploy'
      - 'deploy-beta'
    paths-ignore:
      - '.github/**'
  workflow_dispatch:
    branches-ignore:
      - 'deploy'
      - 'deploy-beta'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 切换到当前分支
        uses: actions/checkout@v3
      - name: 设置Node版本和缓存
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies 🔧
        run: yarn install --frozen-lockfile --registry=https://registry.npmjs.org/
      - name: 编译应用 🔧
        run: yarn build
      - name: 部署应用
        if: ${{ github.ref_name == 'main' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: deploy
          force: false
      - name: 部署测试应用
        if: ${{ github.ref_name == 'dev' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: deploy-beta
          force: false
